version: "2"

services:
  web:
    image: ifgi/origami-caddy
    ports:
      - "80:2015"
      - "443:443"
    environment:
      - WEB_DOMAIN=localhost
      - API_DOMAIN=api.localhost
      - ISSUER_ADDRESS=off
      - USE_STAGING_CA=true
    volumes:
      - caddy-data:/etc/caddy/.caddy
    volumes_from:
      - origami-static
      - api
    networks:
      - api-front
    depends_on:
      - api
      - origami-static
    restart: always
  origami-static:
    image: ifgi/origami
    environment:
      - API_URL=http://api.localhost
  api:
    image: ifgi/origami-backend
    environment:
      - origami_dbuser=admin
      - origami_dbuserpass=admin
      - origami_dbhost=db
    networks:
      - api-front
      - api-back
    depends_on:
      - db
    restart: always
  db:
    image: ifgi/origami-api-mongo
    volumes:
      - mongo-data:/data/db
    environment:
      - origami_dbuser=admin
      - origami_dbuserpass=admin
    command: --auth --storageEngine wiredTiger
    networks:
      - api-back
    restart: always

volumes:
  mongo-data:
    driver: local-persist
    driver_opts:
      mountpoint: /dockervolumes/mongo-data
  caddy-data:
    driver: local-persist
    driver_opts:
      mountpoint: /dockervolumes/caddy-data

networks:
  api-front:
    driver: bridge
  api-back:
    driver: bridge